### ISSUE TITLE
bug with python 3.5.0: bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by mickours** [oar-team/kameleon-helpers#1]
Run the helper script on a recipe I got this error:

```

Step 6 : bootstrap/prepare_appliance/create_appliance
--> Running the step...
[local] virt-make-fs is /usr/bin/virt-make-fs
[local] 
[local] Error: a bytes-like object is required, not 'str'
Starting process: "bash"
Error occured when executing the following command :

> exec_local: |
>   rm -f /home/mercierm/Projects/simctn/build/debian8_batsim/base_debian8_batsim.vmdk
>   # Create an appliance from rootfs directory
>   python /home/mercierm/Projects/simctn/build/debian8_batsim/create_appliance.py /home/mercierm/Projects/simctn/build/debian8_batsim/rootfs.tar.xz \
>     --size 10G \
>     -o /home/mercierm/Projects/simctn/build/debian8_batsim/base_debian8_batsim \
>     --filesystem ext4 \
>     --format vmdk \
>     --append "quiet net.ifnames=0 biosdevname=0"
```

**Comment by mickours** [comment]
I managed to get the stack trace:

```
Traceback (most recent call last):
  File "/home/mercierm/Projects/simctn/build/debian8_batsim/create_appliance.py", line 374, in <module>
    create_appliance(args)
  File "/home/mercierm/Projects/simctn/build/debian8_batsim/create_appliance.py", line 315, in create_appliance
    args.verbose)
  File "/home/mercierm/Projects/simctn/build/debian8_batsim/create_appliance.py", line 250, in create_disk
    input_type = file_type(input_).lower()
  File "/home/mercierm/Projects/simctn/build/debian8_batsim/create_appliance.py", line 119, in file_type
    return output.split(':')[1].strip()
TypeError: a bytes-like object is required, not 'str'
```

**Comment by mickours** [comment]
As a workaround I use `python2` in the bootstrap/prepare_appliance/create_appliance script

**Comment by mickours** [comment]
There is still an issue with python3 in the export_appliance.py script

```
[local] Traceback (most recent call last):
[local]   File "/home/mercierm/Projects/test-kameleon/build/toto/export_appliance.py", line 151, in <module>
[local]     parser.add_argument('file', action="store", type=file,
[local] NameError: name 'file' is not defined
```

**Comment by SalemHarrache** [comment]
Still encoding errors when using `--zerofree` option in python3

```
$ ./export_appliance.py debian7.qcow2 --zerofree -F qcow2 -o debian
INFO: Fill free space with zero

Error: 'str' object has no attribute 'decode'
```
